using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EducationalProduct.Classes
{
    public static class GameResources
    {
        public static readonly Bitmap ApplyButton  = Properties.Resources.ApplyButton;
        public static readonly Bitmap RuleDodgeMeteorite  = Properties.Resources.RuleDodgeMeteorite;
        public static readonly Bitmap RuleCatchBones  = Properties.Resources.RuleCatchBones;
        public static readonly Bitmap RuleCollectPuzzle  = Properties.Resources.RuleCollectPuzzle;
        public static readonly Bitmap RuleRepeatButton  = Properties.Resources.RuleRepeatButton;
        public static readonly Bitmap backgroundExitMenu  = Properties.Resources.backgroundExitMenu;
        public static readonly Bitmap btnClosedOpening  = Properties.Resources.btnClosedOpening;
        public static readonly Bitmap btnQuestion = Properties.Resources.btnQuestion;
        public static readonly Bitmap MenuExit  = Properties.Resources.PlayAgainGameMenu;
        public static readonly Bitmap NoExit = Properties.Resources.NoExit;
        public static readonly Bitmap YesExit = Properties.Resources.YesExit;
        public static readonly Bitmap OpeningRocket = Properties.Resources.OpeningRocket;
        public static readonly Bitmap OpeningTitle = Properties.Resources.OpeningTitle;
        public static readonly Bitmap btnPlayStart = Properties.Resources.btnPlayStart;
        public static readonly Bitmap btnDevInfo = Properties.Resources.btnDevInfo;
        public static readonly Bitmap СharacterRuleScene = Properties.Resources.СharacterRuleScene;
        public static readonly Bitmap txtRuleScene = Properties.Resources.txtRuleScene;
        public static readonly Bitmap CharacterRuleRepeatActionScene = Properties.Resources.CharacterRuleRepeatActionScene;
        public static readonly Bitmap btnNextPlay = Properties.Resources.btnNextPlay;
        public static readonly Bitmap btnBackPlay = Properties.Resources.btnBack;
        public static readonly Bitmap txtRepeatAction1 = Properties.Resources.txtRepeatAction1;
        public static readonly Bitmap txtRepeatAction2 = Properties.Resources.txtRepeatAction2;
        public static readonly Bitmap txtRepeatAction3 = Properties.Resources.txtRepeatAction3;
        public static readonly Bitmap CharacterRuleCatchBonesScene = Properties.Resources.CharacterRuleCatchBonesScene;
        public static readonly Bitmap txtCatchBones1 = Properties.Resources.txtCatchBones1;
        public static readonly Bitmap txtCatchBones2 = Properties.Resources.txtCatchBones2;
        public static readonly Bitmap txtCatchBones3 = Properties.Resources.txtCatchBones3;
        public static readonly Bitmap CharacterRuleCollectPuzzleScene = Properties.Resources.CharacterRuleCollectPuzzleScene;
        public static readonly Bitmap txtCollectPuzzle1 = Properties.Resources.txtCollectPuzzle1;
        public static readonly Bitmap txtCollectPuzzle2 = Properties.Resources.txtCollectPuzzle2;
        public static readonly Bitmap txtCollectPuzzle3 = Properties.Resources.txtCollectPuzzle3;
        public static readonly Bitmap CharacterRuleDodgeMeteoritesScene = Properties.Resources.CharacterRuleDodgeMeteoritesScene;
        public static readonly Bitmap txtDodgeMeteorites1 = Properties.Resources.txtDodgeMeteorites1;
        public static readonly Bitmap txtDodgeMeteorites2 = Properties.Resources.txtDodgeMeteorites2;
        public static readonly Bitmap txtDodgeMeteorites3 = Properties.Resources.txtDodgeMeteorites3;
        public static readonly Bitmap CharacterCatchBones = Properties.Resources.CharacterCatchBones;
        public static readonly Bitmap BackgroundCatchBones = Properties.Resources.BackgroundCatchBones;
        public static readonly Bitmap RedBone =  Properties.Resources.RedBone;
        public static readonly Bitmap OrangeBone = Properties.Resources.OrangeBone;
        public static readonly Bitmap RedBoneSmall = Properties.Resources.RedBoneSmall;
        public static readonly Bitmap OrangeBoneSmall = Properties.Resources.OrangeBoneSmall;
        public static readonly Bitmap BackgroundColleсtPuzzle = Properties.Resources.BackgroundColleсtPuzzle;
        public static readonly Bitmap ShadowPuzzle = Properties.Resources.ShadowPuzzle;
        public static readonly Bitmap SolidRocket = Properties.Resources.SolidRocket;
        public static readonly Bitmap PuzzleBottomLeft = Properties.Resources.PuzzleBottomLeft;
        public static readonly Bitmap PuzzleBottomRight = Properties.Resources.PuzzleBottomRight;
        public static readonly Bitmap PuzzleTopLeft = Properties.Resources.PuzzleTopLeft;
        public static readonly Bitmap PuzzleTopRight = Properties.Resources.PuzzleTopRight;
        public static readonly Bitmap BackgroundDodgeMeteorites = Properties.Resources.BackgroundDodgeMeteorites;
        public static readonly Bitmap RocketDodge = Properties.Resources.RocketDodge;
        public static readonly Bitmap Meteorite = Properties.Resources.Meteorite;
        public static readonly Bitmap LeftButtonDodge = Properties.Resources.LeftButtonDodge;
        public static readonly Bitmap RightButtonDodge = Properties.Resources.RightButtonDodge;
        public static readonly Bitmap BackgroundRepeatAction = Properties.Resources.BackgroundRepeatAction;
        public static readonly Bitmap RedButtonLight = Properties.Resources.RedButtonLight;
        public static readonly Bitmap RedButtonGray = Properties.Resources.RedButtonGray;
        public static readonly Bitmap BlueButtonLight = Properties.Resources.BlueButtonLight;
        public static readonly Bitmap BlueButtonGray = Properties.Resources.BlueButtonGray;
        public static readonly Bitmap YellowButtonLight = Properties.Resources.YellowButtonLight;
        public static readonly Bitmap YellowButtonGray = Properties.Resources.YellowButtonGray;
        public static readonly Bitmap GreenButtonLight = Properties.Resources.GreenButtonLight;
        public static readonly Bitmap GreenButtonGray = Properties.Resources.GreenButtonGray;
        public static readonly Bitmap BackgroundEnd = Properties.Resources.BackgroundEnd;
        public static readonly Bitmap txtEnd = Properties.Resources.txtEnd;
        public static readonly Bitmap btnToStart = Properties.Resources.btnToStart;
        public static readonly Bitmap btnAnswer = Properties.Resources.btnAnswer;
        public static readonly Bitmap txtTestAnswerRepeatAction1 = Properties.Resources.txtTestAnswerRepeatAction1;
        public static readonly Bitmap txtTestAnswerRepeatAction2 = Properties.Resources.txtTestAnswerRepeatAction2;
        public static readonly Bitmap txtTestAnswerRepeatAction3 = Properties.Resources.txtTestAnswerRepeatAction3;
        public static readonly Bitmap txtTestAnswerRepeatAction4 = Properties.Resources.txtTestAnswerRepeatAction4;
        public static readonly Bitmap txtTestQuestionRepeatAction = Properties.Resources.txtTestQuestionRepeatAction;
        public static readonly Bitmap txtTestTipRepeatAction = Properties.Resources.txtTestTipRepeatAction;
        public static readonly Bitmap txtTestAnswerCatchBones1 = Properties.Resources.txtTestAnswerCatchBones1;
        public static readonly Bitmap txtTestAnswerCatchBones2 = Properties.Resources.txtTestAnswerCatchBones2;
        public static readonly Bitmap txtTestAnswerCatchBones3 = Properties.Resources.txtTestAnswerCatchBones3;
        public static readonly Bitmap txtTestAnswerCatchBones4 = Properties.Resources.txtTestAnswerCatchBones4;
        public static readonly Bitmap txtTestQuestionCatchBones = Properties.Resources.txtTestQuestionCatchBones;
        public static readonly Bitmap txtTestTipCatchBones = Properties.Resources.txtTestTipCatchBones;
        public static readonly Bitmap txtTestAnswerCollectPuzzle1 = Properties.Resources.txtTestAnswerCollectPuzzle1;
        public static readonly Bitmap txtTestAnswerCollectPuzzle2 = Properties.Resources.txtTestAnswerCollectPuzzle2;
        public static readonly Bitmap txtTestAnswerCollectPuzzle3 = Properties.Resources.txtTestAnswerCollectPuzzle3;
        public static readonly Bitmap txtTestAnswerCollectPuzzle4 = Properties.Resources.txtTestAnswerCollectPuzzle4;
        public static readonly Bitmap txtTestQuestionCollectPuzzle = Properties.Resources.txtTestQuestionCollectPuzzle;
        public static readonly Bitmap txtTestTipCollectPuzzle = Properties.Resources.txtTestTipCollectPuzzle;
        public static readonly Bitmap txtTestAnswerDodgeMeteorites1 = Properties.Resources.txtTestAnswerDodgeMeteorites1;
        public static readonly Bitmap txtTestAnswerDodgeMeteorites2 = Properties.Resources.txtTestAnswerDodgeMeteorites2;
        public static readonly Bitmap txtTestAnswerDodgeMeteorites3 = Properties.Resources.txtTestAnswerDodgeMeteorites3;
        public static readonly Bitmap txtTestAnswerDodgeMeteorites4 = Properties.Resources.txtTestAnswerDodgeMeteorites4;
        public static readonly Bitmap txtTestQuestionDodgeMeteorites = Properties.Resources.txtTestQuestionDodgeMeteorites;
        public static readonly Bitmap txtTestTipDodgeMeteorites = Properties.Resources.txtTestTipDodgeMeteorites;
        public static readonly Bitmap Success = Properties.Resources.success;
        public static readonly Bitmap btnClosed = Properties.Resources.btnClosed;
        public static readonly Bitmap menuExitGameOpeningScene = Properties.Resources.MenuExit;
        public static readonly Bitmap txtDevInfo = Properties.Resources.txtDevInfo;
        public static readonly Bitmap answerBorder = Properties.Resources.answerBorder;
    }
}
